### ISSUE TITLE
SoftDelete trait...

### ISSUE THREAD

**Issue by jjanne** [mitchellvanw/laravel-doctrine#111]
Can you include a boolean "isDeleted" to the SoftDelete Trait and use this instead of just the DateTime field?  This will speed up the database queries.  Also how about adding some functionality where we could delete the actual record even if it is marked with SoftDelete? Is that possible?

**Comment by kirkbushell** [comment]
It is unlikely that any performance hit is a result of the table and field design. Using a date/time field is a much better solution to just using a boolean, as it provides a context, as well - without having to implement an activity or user log for logging the action (which you can do separately anyway).

The reason for having soft deletion, is because you intend to keep the data, regardless. If you want to actually end up completely removing data, I'd suggest not implementing a soft-delete mechanism on your entity.
