### ISSUE TITLE
Validation - uniqueness

### ISSUE THREAD

**Issue by kirkbushell** [mitchellvanw/laravel-doctrine#38]
Currently if you try and run the uniqueness validation that L4 provides, it will go via Eloquent, setting up a new database connection and do all that double-edged lovely goodness. The problem is, that's not what we want - we need to setup a new DatabasePresenceVerifier that can handle this for us.

This isn't as straight-forward as we'd like. Any ideas as to how this could be handled nicely? Open question/brainstorm session to see what we can come up with.

**Comment by philipbrown** [comment]
Hey Kirk,

Hopefully this is just me being dumb, but I can't get the validation uniqueness to work :sweat:

Whenever I set up a test with an existing user, and then run the validation check, no results are ever returned.

It seems to me that the native query builder won't work in this situation because you need to set the result mapping, e.g http://doctrine-orm.readthedocs.org/en/latest/reference/native-sql.html#examples

Which wouldn't work because you would have no idea what to map at runtime.

Am I missing something really obvious? :flushed:

**Comment by mrsimonbennett** [comment]
+1 to this
